# Generated by Django 2.2.10 on 2020-02-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=15)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
